version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: sociauctor-frontend
    restart: always
    links:
      - backend
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    container_name: sociauctor-backend
    restart: always